# -*- coding: utf-8 -*-
"""managers_21_11_2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bgfAjDwSYUipfspp9ivdFVlxShoTrwA9
"""

primes = [2,3,5,7,11,13,2,2,0]
#rainbow = ['red', 'green', 'blue']
#x = "Привет"
#y = 154
#rainbow = ['red', x, y]
#print (rainbow)
#chars = list('Hello')
#print(chars)
#primes.extend([17,21,23])
#primes.insert(0,'qq')
#primes[2] = "Убил 3"
#print(primes)
#rainbow = rainbow + ['yellow', 'violet']
#print(rainbow)
#9 in primes
primes_cpy = primes.copy()
print(primes_cpy)
print(primes)